### ISSUE TITLE
F12 doesn't work as hotkey

### ISSUE THREAD

**Issue by ghost** [pezcode/ighp#4]
I have an Apple Wireless Keyboard and F12 key is marked there as volume increase.
I have bind it in options but it doesn't work.

win7 x64, ighp 0.1.1 x64, iTunes 12.2

**Comment by pezcode** [comment]
Really late answer, but in case somebody else is stumbling across this:

This is a restriction of [RegisterHotkey](https://msdn.microsoft.com/en-us/library/ms646309.aspx):

> The F12 key is reserved for use by the debugger at all times, so it should not be registered as a hot key. Even when you are not debugging an application, F12 is reserved in case a kernel-mode debugger or a just-in-time debugger is resident.
